project:
  type: website

website:
  title: "jazz-corner"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme: cosmo
    css: styles.css



